### ISSUE TITLE
Gérer les relances.

### ISSUE THREAD

**Issue by Khaali-dev** [12-Monkeys-Developers/cleenmain#26]

**Comment by Qaw** [comment]
- Par arme : via le champ Relance. Attention les dégâts sont mis à jour avec les mêmes dés. Donc une arme à 2D6 utilisent les 2 dés blancs, donc la relance du dé rouge ne change pas le résultat
- Par compétence : via le champ dans la fenêtre de dialogue
- Par arme : via le champ dans la fenêtre de dialogue. Là il n'y a pas de notion de dés blanc ou rouge puisque seul le bon nombre de dés est lancé
J'ai aussi transmis le formulaTooltip de la fenêtre de dialogue sur la formule dans le chat
