### ISSUE TITLE
Automatisation des atouts 

### ISSUE THREAD

**Issue by Khaali-dev** [12-Monkeys-Developers/cleenmain#28]
Ajouter une propriété "bonus" aux objets de type atout. Ce bonus est un {} qui pourra contenir toute sortes de propriétés.
Ces propriétés sont à attribuer via un masque dans la fenetre d'édition des atouts (necessitera peut etre des onglets)
Lors des refresh de l'acteur, les atouts sont parcourus et les bonus attribués.

**Comment by Qaw** [comment]
En lien avec https://github.com/Khaali-dev/cleenmain/issues/12 pour utiliser le même mécanisme

**Comment by Khaali-dev** [comment]
Fait dans 2.1.0
